### PR TITLE
MultiZMW stitching, model structure inputs, log(0) fixes

### PR DESCRIPTION
**Pull request by michaelbrownid**
Hi,

The code now allows multiple ZMWs in a HDF5 file to run inference and stitching. I will  switch my branch from master to dev-v0.1.0 after this to sync with you.
  
   - MultiZMW stitching: multiple zmws in HDF5. readids in hdf5 delinate
      zmw/window boundaries for correct stitching. Many zmws can be sent
      to GPU for inference with results stitched at end.

    - model structure inputs: hardcoded values are now inputs. same
      create_model between training and inference. TODO: should hardcode
      values in python source files and import different models by name
      for continuity

    - fixed log(0) in QV values. Softmax can get numeric 1.0 resulting in
      undefined QV.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by tijyojwad** [comment]
allowlist

**Comment by tijyojwad** [comment]
add to allowlist

**Comment by tijyojwad** [comment]
@michaelbrownid this is an awesome change. would it be okay if we leave a couple of comments on this itself for suggested changes, or would you prefer we fork from this branch and make the changes we're thinking of and push separately?

**Comment by michaelbrownid** [comment]
Logistically, I'm good whatever is easiest to allow us both to be in sync.

**Comment by tijyojwad** [comment]
@michaelbrownid I pushed some updates to your branch itself - logic is the same, just updated some variable names and refactored a bit.

**Comment by tijyojwad** [comment]
add to allowlist

**Review by tijyojwad — APPROVED** [review]

**Comment by tijyojwad** [comment]
rerun tests

**Comment by tijyojwad** [comment]
ok to test

**Comment by tijyojwad** [comment]
rerun tests

**Comment by mike-wendt** [comment]
rerun tests

**Comment by tijyojwad** [comment]
rerun tests

**Comment by raydouglass** [comment]
rerun tests

**Comment by raydouglass** [comment]
add to allowlist

**Pull request merged**
