### PR TITLE
simple_consensus_caller sample fails with negative probabilites.

### PR DESCRIPTION
**Pull request by michaelbrownid**
Hi All!

This is Michael Brown from PacBio.

----
I've installed and tried running the sample test of simple_consensus_caller and get the error "ValueError: all values in error probability array must be between 0 and 1". On the previous version without base qualities, the sample ran correctly.

I believe the code has a bug where softmax values are incorrectly used as probabilities. I documented the bug in code comments and changelog. I wanted to pass onto you before I make changes to fix and possibly misunderstand something.

Let me know if this is the best way to bring these types of issues up.

----

I see this code uses your nemo.core.NeuralModuleFactory as opposed to the previous Keras RNN GRU model. The previous model achieved a 20% reduction in CCS error. Has that been demonstrated on the latest model? If not, that will be the first step.

Best,

---- Michael Brown, PacBio

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by tijyojwad** [comment]
Hi @michaelbrownid ! Thanks for raising this. Looks like this is a bug introduced by, and this is somewhat ironic, another bug fix we pushed as part of https://github.com/clara-parabricks/VariantWorks/pull/134! I'll push a fix for this in a few hours.

In terms of sharing problems, GitHub has support for filing "issues" (https://github.com/clara-parabricks/VariantWorks/issues) . Please feel free to file any bugs/feature requests there. That said, if you have a fix already then a PR is perfectly fine as well :). We're always happy to accept contributions from the community!

We have also validated that the VariantWorks model (before the current bug) achieves the same level of accuracy as the pipeline we shared earlier.

**Comment by tijyojwad** [comment]
@michaelbrownid we merged a fix for it in #137 . It should be in master now. Can you pull the latest code and try it out again?

**Comment by tijyojwad** [comment]
Closing as it's addressed in #137

**Pull request closed without merging**
